import { LegalPageLayout } from '@/components/LegalPageLayout';

export default function AIDisclaimerPage() {
  return (
    <LegalPageLayout title="AI Disclaimer and Alpha/Beta Notice" lastUpdated="November 2025">
      <div className="space-y-4 text-sm">
        <p>
          This AI Disclaimer and Alpha/Beta Notice explains the nature and limitations of Zombify, a product operated by Firststab (Pty) Ltd, a company incorporated in the Republic of South Africa ("we," "our," or "us").
        </p>
        <p>
          By using Zombify, you acknowledge that all outputs are generated by artificial intelligence systems and are subject to the limitations described below.
        </p>
        <p>
          This document should be read together with our{' '}
          <a href="/terms" className="underline hover:opacity-70">Terms of Service</a>,{' '}
          <a href="/privacy" className="underline hover:opacity-70">Privacy Policy</a>, and{' '}
          <a href="/cookies" className="underline hover:opacity-70">Cookie Policy</a>.
        </p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">1. Nature of AI-Generated Output</h3>
        <p>1.1 All feedback, insights, or recommendations produced by Zombify are automatically generated by artificial intelligence ("AI") models.</p>
        <p>1.2 These outputs are provided for informational and educational purposes only and do not constitute professional advice.</p>
        <p>1.3 Zombify does not guarantee the accuracy, completeness, reliability, or suitability of any AI-generated output.</p>
        <p>1.4 Users must exercise discretion and professional judgment when interpreting or applying any AI-generated results.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">2. Model Sources</h3>
        <p>2.1 Zombify currently uses:</p>
        <p className="pl-4">a. OpenAI GPT-5 for visual and textual analysis.</p>
        <p className="pl-4">b. Browser-side text extraction tools (Tesseract) for capturing interface text.</p>
        <p>2.2 All processing occurs securely through approved APIs.</p>
        <p>2.3 Zombify does not fine-tune or train external AI models using uploaded content.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">3. Limitations</h3>
        <p>3.1 The AI system:</p>
        <p className="pl-4">a. Cannot detect all accessibility, usability, or compliance issues.</p>
        <p className="pl-4">b. May misinterpret colors, layouts, or contextual language.</p>
        <p className="pl-4">c. Should not be used to analyze confidential or sensitive data.</p>
        <p className="pl-4">d. May vary in accuracy or reliability across model updates or versions.</p>
        <p>3.2 Zombify provides no warranty or guarantee of correctness, performance, or results.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">4. Alpha/Beta Phase Notice</h3>
        <p>4.1 Zombify is currently operating in an alpha/beta development phase.</p>
        <p>4.2 During this phase:</p>
        <p className="pl-4">a. Features may change, malfunction, or be removed without notice.</p>
        <p className="pl-4">b. Data loss, downtime, or partial functionality may occur.</p>
        <p className="pl-4">c. User feedback and anonymised telemetry may be used for product improvement.</p>
        <p>4.3 Zombify provides the Service on a trial basis during its alpha/beta phase and reserves the right to modify, suspend, or discontinue any feature at any time without notice.</p>
        <p>4.4 By using the Service, you acknowledge and accept these alpha/beta conditions.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">5. Responsibility</h3>
        <p>5.1 The User is solely responsible for:</p>
        <p className="pl-4">a. Deciding whether to act on any AI-generated feedback or recommendations.</p>
        <p className="pl-4">b. Ensuring that uploaded content does not contain personal, private, or confidential data.</p>
        <p className="pl-4">c. Managing data shared publicly or through share links.</p>
        <p>5.2 Zombify is not liable for:</p>
        <p className="pl-4">a. Misinterpretation, inaccuracy, or reliance on AI-generated results.</p>
        <p className="pl-4">b. Loss of data, revenue, or reputation.</p>
        <p className="pl-4">c. Any downstream or consequential impact arising from applying AI-generated insights.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">6. Commercial Use</h3>
        <p>6.1 Users may use Zombify's AI outputs for commercial or non-commercial purposes.</p>
        <p>6.2 Zombify claims no ownership over resulting designs, derivative works, or decisions made using the Service.</p>
        <p>6.3 Use of AI outputs for commercial purposes remains the sole responsibility of the User.</p>
        <p>6.4 Zombify disclaims any liability arising from third-party reliance on such outputs.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">7. Data Handling</h3>
        <p>7.1 Uploaded screenshots and AI analyses are stored according to your account plan (ten [10] for Free users; sixty [60] for Pro users).</p>
        <p>7.2 Older analyses are automatically deleted and cannot be recovered.</p>
        <p>7.3 Account deletion permanently removes all associated data from Zombify's databases.</p>
        <p>7.4 You may request deletion by emailing hi@zombify.ai.</p>
        <p>7.5 Analytical data may be retained in anonymised or aggregated form for performance improvement.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">8. Future Model Updates</h3>
        <p>8.1 AI models and analytical engines may be updated, replaced, or adjusted without notice.</p>
        <p>8.2 Different model versions may produce varied interpretations or outputs for the same uploaded content.</p>

        <div className="border-t border-black/20 my-6"></div>

        <h3 className="font-bold text-base">9. Contact</h3>
        <p>For any questions, feedback, or concerns about AI-generated content or system reliability, contact:</p>
        <p>Email: <a href="mailto:hi@zombify.ai" className="underline hover:opacity-70">hi@zombify.ai</a></p>
      </div>
    </LegalPageLayout>
  );
}
